// <auto-generated />
using System;
using DrivingSchoolAPI.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DrivingSchoolAPI.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20241025103543_SecondMigration")]
    partial class SecondMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("DrivingSchoolAPI.Entities.City", b =>
                {
                    b.Property<int>("IdCity")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_miasto");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCity"));

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazwa");

                    b.HasKey("IdCity");

                    b.ToTable("miasto", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Client", b =>
                {
                    b.Property<int>("IdClient")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_klient");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClient"));

                    b.Property<DateOnly>("ClientBirthDay")
                        .HasColumnType("date")
                        .HasColumnName("data_urodzenia");

                    b.Property<string>("ClientEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("adres_email");

                    b.Property<string>("ClientFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imie");

                    b.Property<int?>("ClientFlatNumber")
                        .HasColumnType("int")
                        .HasColumnName("numer_lokalu");

                    b.Property<string>("ClientHouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numer_domu");

                    b.Property<int>("ClientIdCity")
                        .HasColumnType("int")
                        .HasColumnName("id_miasto");

                    b.Property<int>("ClientIdZipCode")
                        .HasColumnType("int")
                        .HasColumnName("id_kod_pocztowy");

                    b.Property<string>("ClientLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("ClientPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("haslo");

                    b.Property<string>("ClientPhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nr_telefonu");

                    b.Property<bool>("ClientStatus")
                        .HasColumnType("bit")
                        .HasColumnName("czy_kursant");

                    b.HasKey("IdClient");

                    b.HasIndex("ClientIdCity");

                    b.HasIndex("ClientIdZipCode");

                    b.ToTable("klient", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.ClientService", b =>
                {
                    b.Property<int>("IdClientService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_klient_usluga");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdClientService"));

                    b.Property<int>("ClientId")
                        .HasColumnType("int")
                        .HasColumnName("id_klient");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime2")
                        .HasColumnName("data_zakupu");

                    b.Property<int>("Quantity")
                        .HasColumnType("int")
                        .HasColumnName("ilosc");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int")
                        .HasColumnName("id_usluga");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("stan");

                    b.HasKey("IdClientService");

                    b.HasIndex("ClientId");

                    b.HasIndex("ServiceId");

                    b.ToTable("klient_usluga", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Instructor", b =>
                {
                    b.Property<int>("IdInstructor")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_instruktor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstructor"));

                    b.Property<string>("InstructorEmail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("InstructorFirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("imie");

                    b.Property<string>("InstructorLastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazwisko");

                    b.Property<string>("InstructorPhhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("numer_telefonu");

                    b.Property<bool>("InstructorPratice")
                        .HasColumnType("bit")
                        .HasColumnName("czy_prowadzi_praktyke");

                    b.Property<bool>("InstructorTheory")
                        .HasColumnType("bit")
                        .HasColumnName("czy_prowadzi_teorie");

                    b.HasKey("IdInstructor");

                    b.ToTable("instruktor", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.InstructorDetails", b =>
                {
                    b.Property<int>("IdInstructorDetails")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_szczegoly_instruktor");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdInstructorDetails"));

                    b.Property<int>("IdInstructor")
                        .HasColumnType("int")
                        .HasColumnName("id_instruktor");

                    b.Property<int>("InstructorCityId")
                        .HasColumnType("int")
                        .HasColumnName("id_miasto");

                    b.Property<int?>("InstructorFlatNumber")
                        .HasColumnType("int")
                        .HasColumnName("nr_lokalu");

                    b.Property<string>("InstructorHouseNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nr_domu");

                    b.Property<string>("InstructorPassword")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("haslo");

                    b.Property<decimal>("InstructorPesel")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("pesel");

                    b.Property<string>("InstructorStreet")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ulica");

                    b.Property<int>("InstructorZipCodeId")
                        .HasColumnType("int")
                        .HasColumnName("id_kod_pocztowy");

                    b.HasKey("IdInstructorDetails");

                    b.HasIndex("IdInstructor")
                        .IsUnique();

                    b.HasIndex("InstructorCityId");

                    b.HasIndex("InstructorZipCodeId");

                    b.ToTable("szczegoly_instruktor", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Promotion", b =>
                {
                    b.Property<int>("IdPromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_promocja");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdPromotion"));

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasColumnName("aktywna");

                    b.Property<string>("PromotionDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis_promocja");

                    b.Property<string>("PromotionName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazwa_promocja");

                    b.Property<decimal>("PromotionValue")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("wartosc_promocja");

                    b.HasKey("IdPromotion");

                    b.ToTable("promocja", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Service", b =>
                {
                    b.Property<int>("IdService")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usluga");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdService"));

                    b.Property<string>("ServiceDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("opis");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nazwa_usluga");

                    b.Property<decimal>("ServiceNetPrice")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("cena_netto");

                    b.Property<string>("ServiceType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("typ_usluga");

                    b.Property<int>("ServiceVatRate")
                        .HasColumnType("int")
                        .HasColumnName("stawka_vat");

                    b.HasKey("IdService");

                    b.ToTable("usluga", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.ServicePromotion", b =>
                {
                    b.Property<int>("IdServicePromotion")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_usluga_promocja");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdServicePromotion"));

                    b.Property<DateOnly>("AssigmentDate")
                        .HasColumnType("date")
                        .HasColumnName("data_przypisania");

                    b.Property<int>("IdPromotion")
                        .HasColumnType("int")
                        .HasColumnName("id_promocja");

                    b.Property<int>("IdService")
                        .HasColumnType("int")
                        .HasColumnName("id_usluga");

                    b.HasKey("IdServicePromotion");

                    b.HasIndex("IdPromotion")
                        .IsUnique();

                    b.HasIndex("IdService")
                        .IsUnique();

                    b.ToTable("usluga_promocja", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Status", b =>
                {
                    b.Property<int>("IdStatus")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_status");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdStatus"));

                    b.Property<string>("StatusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("status");

                    b.HasKey("IdStatus");

                    b.ToTable("status", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.TraineeCourse", b =>
                {
                    b.Property<int>("IdTraineeCourse")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_kursant_kurs");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdTraineeCourse"));

                    b.Property<DateOnly>("EndDate")
                        .HasColumnType("date")
                        .HasColumnName("data_zakonczenia");

                    b.Property<int>("IdClient")
                        .HasColumnType("int")
                        .HasColumnName("id_klient");

                    b.Property<int>("IdService")
                        .HasColumnType("int")
                        .HasColumnName("id_usluga");

                    b.Property<int>("IdStatus")
                        .HasColumnType("int")
                        .HasColumnName("id_status");

                    b.Property<bool>("MedicalCheck")
                        .HasColumnType("bit")
                        .HasColumnName("badania_lekarskie");

                    b.Property<decimal>("PESEL")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("PESEL");

                    b.Property<string>("PKK")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("pkk");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date")
                        .HasColumnName("data_rozpoczecia");

                    b.HasKey("IdTraineeCourse");

                    b.HasIndex("IdClient")
                        .IsUnique();

                    b.HasIndex("IdService")
                        .IsUnique();

                    b.HasIndex("IdStatus");

                    b.ToTable("kursant_kurs", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.ZipCode", b =>
                {
                    b.Property<int>("IdZipCode")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id_kod_pocztowy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdZipCode"));

                    b.Property<string>("ZipCodeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("kod_pocztowy");

                    b.HasKey("IdZipCode");

                    b.ToTable("kod_pocztowy", (string)null);
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Client", b =>
                {
                    b.HasOne("DrivingSchoolAPI.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("ClientIdCity")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolAPI.Entities.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("ClientIdZipCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("ZipCode");
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.ClientService", b =>
                {
                    b.HasOne("DrivingSchoolAPI.Entities.Client", "Client")
                        .WithMany("ClientServices")
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolAPI.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.InstructorDetails", b =>
                {
                    b.HasOne("DrivingSchoolAPI.Entities.Instructor", "Instructor")
                        .WithOne("InstructorDetails")
                        .HasForeignKey("DrivingSchoolAPI.Entities.InstructorDetails", "IdInstructor")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolAPI.Entities.City", "City")
                        .WithMany()
                        .HasForeignKey("InstructorCityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolAPI.Entities.ZipCode", "ZipCode")
                        .WithMany()
                        .HasForeignKey("InstructorZipCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("Instructor");

                    b.Navigation("ZipCode");
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.ServicePromotion", b =>
                {
                    b.HasOne("DrivingSchoolAPI.Entities.Promotion", "Promotion")
                        .WithOne("ServicePromotion")
                        .HasForeignKey("DrivingSchoolAPI.Entities.ServicePromotion", "IdPromotion")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolAPI.Entities.Service", "Service")
                        .WithOne("ServicePromotion")
                        .HasForeignKey("DrivingSchoolAPI.Entities.ServicePromotion", "IdService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Promotion");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.TraineeCourse", b =>
                {
                    b.HasOne("DrivingSchoolAPI.Entities.Client", "Client")
                        .WithOne("TraineeCourse")
                        .HasForeignKey("DrivingSchoolAPI.Entities.TraineeCourse", "IdClient")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolAPI.Entities.Service", "Service")
                        .WithOne("TraineeCourse")
                        .HasForeignKey("DrivingSchoolAPI.Entities.TraineeCourse", "IdService")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DrivingSchoolAPI.Entities.Status", "Status")
                        .WithMany()
                        .HasForeignKey("IdStatus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");

                    b.Navigation("Service");

                    b.Navigation("Status");
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Client", b =>
                {
                    b.Navigation("ClientServices");

                    b.Navigation("TraineeCourse")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Instructor", b =>
                {
                    b.Navigation("InstructorDetails");
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Promotion", b =>
                {
                    b.Navigation("ServicePromotion")
                        .IsRequired();
                });

            modelBuilder.Entity("DrivingSchoolAPI.Entities.Service", b =>
                {
                    b.Navigation("ServicePromotion")
                        .IsRequired();

                    b.Navigation("TraineeCourse")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
